<?php 

return [
    'equipment'=> [
        "create" => 'Tambah data equipment berhasil',
        "update" => 'Ubah data equipment berhasil',
        "delete" => 'Data equipment berhasil dihapus',
        "view" => 'Berhasil mendapatkan data equipment',
        "not_found" => 'Data equipment tidak ditemukan',
    ],
    'formatexport'=> [
        "create" => 'Tambah data formatexport berhasil',
        "update" => 'Ubah data formatexport berhasil',
        "delete" => 'Data formatexport berhasil dihapus',
        "view" => 'Berhasil mendapatkan data formatexport',
        "not_found" => 'Data formatexport tidak ditemukan',
    ],
    'laporan'=> [ 
        "view" => 'Berhasil mendapatkan data laporan presentasi', 
    ],
    'nonrutinvibrasi'=> [
        "create" => 'Tambah data non rutin vibrasi berhasil',
        "update" => 'Ubah data non rutin vibrasi berhasil',
        "delete" => 'Data non rutin vibrasi berhasil dihapus',
        "view" => 'Berhasil mendapatkan data non rutin vibrasi',
        "not_found" => 'Data non rutin vibrasi tidak ditemukan',
        "failed" => 'Gagal membuat data non rutin vibrasi',
    ],
    'rekomendasi'=> [
        "create" => 'Tambah data rekomendasi berhasil',
        "update" => 'Ubah data rekomendasi berhasil',
        "delete" => 'Data rekomendasi berhasil dihapus',
        "view" => 'Berhasil mendapatkan data rekomendasi',
        "not_found" => 'Data rekomendasi tidak ditemukan',
        "failed" => 'Gagal membuat data rekomendasi',
    ],
    'statistik'=> [
        "create" => 'Tambah data statistik berhasil',
        "update" => 'Ubah data statistik berhasil',
        "delete" => 'Data statistik berhasil dihapus',
        "view" => 'Berhasil mendapatkan data statistik',
        "not_found" => 'Data statistik tidak ditemukan',
        "failed" => 'Gagal mendapatkan data statistik',
    ],
    'termografi'=> [
        "create" => 'Tambah data termografi berhasil',
        "update" => 'Ubah data termografi berhasil',
        "delete" => 'Data termografi berhasil dihapus',
        "view" => 'Berhasil mendapatkan data termografi',
        "not_found" => 'Data termografi tidak ditemukan',
        "failed_create" => 'Gagal membuat data termografi',
        "failed_update" => 'Gagal mengubah data termografi',
    ],
    'tribologi'=> [
        "create" => 'Tambah data tribologi berhasil',
        "update" => 'Ubah data tribologi berhasil',
        "delete" => 'Data tribologi berhasil dihapus',
        "view" => 'Berhasil mendapatkan data tribologi',
        "not_found" => 'Data tribologi tidak ditemukan',
        "failed_create" => 'Gagal membuat data tribologi',
        "failed_update" => 'Gagal mengubah data tribologi', 
    ],
    'unit_item'=> [
        "create" => 'Tambah data unit item berhasil',
        "update" => 'Ubah data unit item berhasil',
        "delete" => 'Data unit item berhasil dihapus',
        "view" => 'Berhasil mendapatkan data unit item',
        "not_found" => 'Data unit item tidak ditemukan',
        "failed_create" => 'Gagal membuat data unit item',
        "failed_update" => 'Gagal mengubah data unit item', 

    ],
    'unitpembangkit'=> [
      "create" => 'Tambah data unit pembangkit berhasil',
      "update" => 'Ubah data unit pembangkit berhasil',
      "delete" => 'Data unit pembangkit berhasil dihapus',
      "view" => 'Berhasil mendapatkan data unit pembangkit',
      "not_found" => 'Data unit pembangkit tidak ditemukan',
      "failed_create" => 'Gagal membuat data unit pembangkit',
      "failed_update" => 'Gagal mengubah data unit pembangkit', 
    ],
    'usermanagement'=> [
      "create" => 'Tambah data user management berhasil',
      "update" => 'Ubah data user management berhasil',
      "delete" => 'Data user management berhasil dihapus',
      "view" => 'Berhasil mendapatkan data user management',
      "not_found" => 'Data user management tidak ditemukan',
      "failed_create" => 'Gagal membuat data user management',
      "failed_update" => 'Gagal mengubah data user management', 
      "failed_delete" => 'Gagal menghapus data user management karena dipakai oleh data transaksi',
    ],
    'role'=> [
      "create" => 'Tambah data role berhasil',
      "update" => 'Ubah data role berhasil',
      "delete" => 'Data role berhasil dihapus',
      "view" => 'Berhasil mendapatkan data role',
      "not_found" => 'Data role tidak ditemukan',
      "failed_create" => 'Gagal membuat data role',
      "failed_update" => 'Gagal mengubah data role', 
    ],
    'vibrasi'=> [
      "create" => 'Tambah data vibrasi berhasil',
      "update" => 'Ubah data vibrasi berhasil',
      "delete" => 'Data vibrasi berhasil dihapus',
      "view" => 'Berhasil mendapatkan data vibrasi',
      "not_found" => 'Data vibrasi tidak ditemukan',
      "failed_create" => 'Gagal membuat data vibrasi',
      "failed_update" => 'Gagal mengubah data vibrasi',  
    ],
];